apiVersion: v1
kind: Secret
metadata:
    name: example-application
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mnzlElB+3FjFKao7,iv:i8XqDWpesVULBwKUyiNVy5lQ7MY32mab/p5wo9PyG2A=,tag:vkAZHOMWovUpPQjLWLestA==,type:str]
    password: ENC[AES256_GCM,data:XtOo6CeeOqr1gw==,iv:V4IohSlXrfGm1QMnXtY/NhoqMppEgfrrJo92LuQhDEc=,tag:JrR7WCiqM8JKUW+oKKnLAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbGU2bjFaWWtOeXlrOHl3
            Q1htd2RtSlBpRG90SUpIWHlaRlROWkYzWmk0ClRBR2dzWXV0bU0wUDRpQjE4OG1h
            ZXAvalEwd0NoTmUwU1U1TDVTb2pycXcKLS0tIEFIajdsZHpXWUFFNytuc0dvMC93
            cThmNGlxaWFlNFVNN3p3cUlQL3J1NHMKiz1LWJfw8x+UIn2Kwp4aT17Wg0pSYw6B
            aNwuDec4Gx8OvvxDUz7/xaHFiISPJbkmaVO8Da+hqghG1UwwjuqDQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1deeq9quljsdstn4eqdd68uyu87vwajq7yljcsj3y96xvggvuxv2q35wq4w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUDB4SjJoQi9uOWFOQnVh
            blZwZkJ1S293bjJWTEdQeS8vcEFhci9hMGk4ClVzZmduNmQwTmQ1R0ZNV0QxbUVB
            VWhaWW1CTHNKRGdIS0xTWkpqdER2K2MKLS0tIGNjQXp0bm9lR3ZudlpmOFFveGJN
            TVhtMWQ0ZE4wZ2NnREZ4VXgxYnpTQWsKUIzJHV0oKjxTSA2d8lP3XZ8WrGHbYaOE
            l/q1G+XRuOpCCldyxELui6W09rQsk//zrlwT8MVwDE17EIWx5rcVQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1an9w2y5s6ancclzsdlkt334ef97k2m80yw9p5fsz26zu6qw45uqq25t7dg
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-30T18:26:29Z"
    mac: ENC[AES256_GCM,data:W6JZXuZzS1vrtqBAsctWkkm3Tp/RRHVnklq/1HM+z/O06OXH0OyPG7RhW6mo3dvG+KPoft+qTbuUWE9k8tKSnJMtmXEZhcVaq/ZTRDwicE77630n60it+0ZfGbbEfOGPOYQ0jF6IRKA7w7kww5PbnGDPba+U4n++OhObTmThp4Q=,iv:rIy3HgZg+cJC2p+Z/tn8KmUilyOigKh0LJ/+dt/wakU=,tag:bT59uMcHqajLXO8DkTJ8gw==,type:str]
    version: 3.13.3
